import {BookButton} from '../../components/SiteChrome';
import {EMAIL} from '../../lib/content';
export const metadata={title:'Plan Your Visit | Corral Creek Lodge',description:'Directions, check-in information, pet policies, and contact details for your Corral Creek Lodge stay.'};
export default function Visit(){return <main id="main" className="inner-main"><section className="page-intro section"><p className="eyebrow">WE’LL SEE YOU UP THE RIVER</p><h1>A little planning.<br/><em>An easier arrival.</em></h1><p>We’re about nine miles north of Kernville, across the road from the Kern River and surrounded by the Sequoia National Forest.</p></section><section className="arrival section compact"><img src="/images/aerial.jpg" alt="The lodge, mountain slopes, and road beside the Kern River"/><div><p className="eyebrow">FIND YOUR WAY HERE</p><h2>The scenic route<br/>ends <em>here.</em></h2><p>Use Corral Creek Lodge as your navigation destination. Check mountain road conditions when planning your route, especially for high-elevation approaches.</p><a className="button" href="https://www.google.com/maps/search/?api=1&query=Corral+Creek+Lodge+Kernville">Open directions ↗</a><a className="text-link" href="https://roads.dot.ca.gov/">Check California road conditions ↗</a></div></section><section className="section faq-layout"><div><p className="eyebrow">THE ESSENTIALS</p><h2>Good to <em>know.</em></h2><p>Need a hand planning your stay?<br/>We’re happy to hear from you.</p><a className="text-link" href="tel:+17603763601">760-376-3601 ↗</a></div><div className="faqs">{[
 ['When are check-in and check-out?','The lodge’s published check-in time is 3 PM and check-out is 11 AM. Contact the lodge to discuss arrival arrangements.'],
 ['Can I bring my pet?','Pets are welcome in designated pet-friendly rooms. Pets must be leashed and may not be left unattended in the room. Confirm availability, fees, and current terms when reserving.'],
 ['Do the rooms have kitchens?','Rooms have kitchenettes. Confirm the equipment and layout of your exact room in the reservation system or with the lodge. Outdoor barbecue facilities are also available.'],
 ['How do I book or change a reservation?','Use Find your stay to open the live ResNexus reservation system. For an existing reservation, use your confirmation details or call the lodge for assistance.'],
 ['What about accessibility?','Please contact the lodge before booking to discuss the entrance, parking, stairs, bathroom, and room features you need. Specific physical accessibility details must be confirmed for your selected room.'],
 ['Is the river right outside?','The river is across the road from the lodge. Conditions vary; ask about suitable access and follow current local guidance.'],
 ['What are the cancellation terms?','Cancellation and deposit terms vary for standard, group, holiday, and special-event bookings. Read the lodge’s full policies and the terms shown for your reservation before paying.']
 ].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}<a className="text-link" href="https://www.corralcreekresort.com/Policies-.html">Read the current booking policies ↗</a></div></section><section className="section contact-panel"><p className="eyebrow">A REAL PERSON. A LITTLE LOCAL KNOWLEDGE.</p><h2>Let’s plan your <em>getaway.</em></h2><div><a href="tel:+17603763601">Call 760-376-3601 ↗</a><a href={`mailto:${EMAIL}`}>Email the lodge ↗</a><BookButton/></div></section></main>}
