'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {BOOKING_URL,EMAIL} from '../lib/content';
import {LogoMark} from './Logo';
import SocialIcon from './SocialIcon';
export function Brand(){return <Link className="brand" href="/" aria-label="Corral Creek Lodge home"><LogoMark/><span className="brand-words">CORRAL CREEK<span>LODGE · KERNVILLE, CALIFORNIA</span></span></Link>}
export function BookButton({className='button',children=<>Book now <span aria-hidden="true">→</span></>}:{className?:string,children?:React.ReactNode}){return <button className={className} onClick={()=>window.dispatchEvent(new Event('open-booking'))}>{children}</button>}
export function SiteHeader(){const [menu,setMenu]=useState(false);const [still,setStill]=useState(false);const path=usePathname();
useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{let saved=false;try{saved=localStorage.getItem('corral-motion')==='off'}catch{}const value=reduced.matches||saved;setStill(value);document.documentElement.dataset.motion=value?'off':'on'};update();reduced.addEventListener('change',update);return()=>reduced.removeEventListener('change',update)},[]);
function motion(){const value=window.matchMedia('(prefers-reduced-motion: reduce)').matches||!still;setStill(value);document.documentElement.dataset.motion=value?'off':'on';try{localStorage.setItem('corral-motion',value?'off':'on')}catch{}window.dispatchEvent(new Event('motion-change'))}
return <><a className="skip-link" href="#main">Skip to content</a><header className={`site-header ${path==='/'?'home-header':'inner-header'}`}><Brand/><nav aria-label="Main navigation" className={menu?'nav-open':''} id="main-nav" onKeyDown={e=>{if(e.key==='Escape'){setMenu(false);document.getElementById('menu-button')?.focus()}}}>{[['/stay','The stay'],['/explore','The valley'],['/#guestbook','Guestbook'],['/visit','Plan your visit']].map(([url,title])=><Link href={url} key={url} aria-current={path===url?'page':undefined} onClick={()=>setMenu(false)}>{title}</Link>)}</nav><div className="header-actions"><BookButton className="button cream"/><button id="menu-button" className="menu-toggle" aria-expanded={menu} aria-controls="main-nav" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button></div></header><button className="motion-toggle" aria-pressed={still} onClick={motion}><span className="motion-label">{still?'Motion off':'Motion on'}</span> <span aria-hidden="true">{still?'◌':'◉'}</span></button><BookingDialog/></>}
function BookingDialog(){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const open=()=>{if(!ref.current?.open)ref.current?.showModal()};window.addEventListener('open-booking',open);return()=>window.removeEventListener('open-booking',open)},[]);return <dialog className="booking-dialog" ref={ref} aria-labelledby="booking-title" onClick={e=>{if(e.target===ref.current)ref.current.close()}}><button className="dialog-close" aria-label="Close booking information" onClick={()=>ref.current?.close()}>×</button><p className="eyebrow">YOUR NEXT CHAPTER</p><h2 id="booking-title">A good place<br/>to <em>land.</em></h2><p>Choose your dates, guests, and room in our secure ResNexus reservation system. You’ll see current availability, rates, and booking terms there.</p><div className="booking-notice"><strong>Live reservations</strong><p>This preview connects to the lodge’s real booking system. Reservations completed there are real.</p></div><a className="button" href={BOOKING_URL}>Continue to live booking <span aria-hidden="true">↗</span></a><a className="booking-call" href="tel:+17603763601">Prefer to talk? Call 760-376-3601</a></dialog>}
export function SiteFooter(){return <><section className="closing"><p className="eyebrow">THE MOUNTAINS ARE CALLING</p><h2>Leave a little room<br/>for <em>getting away.</em></h2><BookButton className="button cream"/></section><footer><div className="footer-top"><div><Brand/><p>Your home base for the Kern River Valley.<br/>Nine miles north of Kernville, California.</p></div><div><p className="eyebrow">COME WANDER</p><Link href="/stay">The stay</Link><Link href="/explore">Explore the valley</Link><Link href="/gallery">A look around</Link><Link href="/visit">Plan your visit</Link></div><div><p className="eyebrow">SAY HELLO</p><a href="tel:+17603763601">760-376-3601</a><a href={`mailto:${EMAIL}`}>{EMAIL}</a><a href="https://www.google.com/maps/search/?api=1&query=Corral+Creek+Lodge+Kernville">Get directions ↗</a></div><div><p className="eyebrow">FOLLOW ALONG</p><a className="footer-social" href="https://www.instagram.com/corralcreeklodge/"><SocialIcon name="Instagram"/>Instagram</a><a className="footer-social" href="https://www.facebook.com/CorralCreekResort"><SocialIcon name="Facebook"/>Facebook</a><a className="footer-social" href="https://twitter.com/corrallodge"><SocialIcon name="X"/>X / Twitter</a><a className="footer-social" href="https://www.tripadvisor.com/Hotel_Review-g32556-d3225195-Reviews-Corral_Creek_Lodge-Kernville_California.html"><SocialIcon name="Tripadvisor"/>Tripadvisor</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Corral Creek Lodge</span><div><Link href="/accessibility">Accessibility</Link><Link href="/credits">Photo credits</Link><a href="https://www.corralcreekresort.com/Policies-.html">Booking policies ↗</a><a href="https://www.corralcreekresort.com/Privacy-Policy.html">Privacy ↗</a></div><span>DESIGN PREVIEW</span></div></footer><div className="mobile-book"><span>A little closer to the wild.</span><BookButton/></div></>}
