export const BOOKING_URL='https://resnexus.com/resnexus/reservations/book/F4D3BD27-C750-49DC-9659-296EAB01301B';
export const PHONE='760-376-3601';
export const EMAIL='reservations@corralcreekresort.com';
export const rooms=[
 {slug:'king-studio',name:'Comfort King',label:'A little space for two',image:'king-clean',alt:'King bed and kitchenette in a Corral Creek Lodge studio',beds:'1 king bed',guests:'Up to 2 guests',pet:'Select pet-friendly rooms',description:'Unpack, put the kettle on, and settle into your own mountain hideaway. A king bed and kitchenette make an easy home base for days in the valley.',details:['King bed','Kitchenette','Wi-Fi','Television','Select pet-friendly options'],note:'Photos show a representative king room. Layout and features vary by room; confirm your exact selection in the reservation system.'},
 {slug:'double-queen-studio',name:'Double Queen',label:'Good company. Great outdoors.',image:'queens-clean',alt:'Two queen beds in a Corral Creek Lodge studio',beds:'2 queen beds',guests:'Up to 4 guests',pet:'Select pet-friendly rooms',description:'Bring your favorite people and make a little room for adventure. Two queen beds and a kitchenette give your group a comfortable place to come back to.',details:['Two queen beds','Kitchenette','Wi-Fi','Television','Select pet-friendly options'],note:'Photos show a representative double queen room. Layout and features vary by room; confirm your exact selection in the reservation system.'},
 {slug:'pet-friendly-king',name:'Pet-Friendly King',label:'Your dog gets a getaway, too',image:'king-clean',alt:'Representative king studio interior; pet room layouts vary',beds:'1 king bed',guests:'Up to 2 guests',pet:'Designated pet-friendly room',description:'A king studio and kitchenette for you and your dog. Select a designated pet room in live booking.',details:['King bed','Kitchenette','Wi-Fi','Television','Pet-friendly designation; fees and terms apply'],note:'Representative king interior, not a photograph of a guaranteed pet room. Confirm exact layout, pet fees and availability before booking.'},
 {slug:'pet-friendly-double-queen',name:'Pet-Friendly Double Queen',label:'The whole pack, together',image:'queens-clean',alt:'Representative double queen interior; pet room layouts vary',beds:'2 queen beds',guests:'Up to 4 guests',pet:'Designated pet-friendly room',description:'Two queen beds, a kitchenette and a place for your dog. Select a designated pet room in live booking.',details:['Two queen beds','Kitchenette','Wi-Fi','Television','Pet-friendly designation; fees and terms apply'],note:'Representative double queen interior, not a photograph of a guaranteed pet room. Confirm exact layout, pet fees and availability before booking.'}
];
export const experiences=[
 {id:'river',category:'Adventure',name:'Follow the whitewater',place:'KERN RIVER',image:'rafting',alt:'Whitewater rafting on the Kern River',description:'Make a day of the river with a guided rafting trip. Let a local outfitter help you choose a trip for your experience level and the season.',url:'https://www.kernrafting.com/',link:'Explore Kern River Outfitters',note:'Seasonal trips; check current conditions and operator requirements.'},
 {id:'forest',category:'Nature',name:'Stand among giants',place:'BEYOND KERNVILLE',image:'forest',alt:'Giant sequoia trees at the Trail of 100 Giants',description:'Take the scenic route to the Trail of 100 Giants and spend time beneath the sequoias. This is a day trip beyond town, with seasonal road access.',url:'https://www.fs.usda.gov/r05/sequoia/recreation/giant-sequoia-national-monument-south-0',link:'Plan a forest visit',note:'Check Forest Service road and trail status before leaving.'},
 {id:'town',category:'Town & culture',name:'A little local history',place:'KERNVILLE',image:'museum',alt:'Kern Valley Museum',description:'Get to know the stories of the valley at Kern Valley Museum, then leave time to wander through town and browse local shops.',url:'https://www.kernvalleymuseum.org/',link:'Visit the museum website',note:'Confirm opening hours directly with the museum.'},
 {id:'food',category:'Food & drink',name:'A taste of the valley',place:'KERNVILLE',image:'kernville',alt:'Historic downtown Kernville streetscape, photographed in 2007',description:'Bring your appetite to Kernville. Explore local dining and make time for a meal at Kern River Brewing Company’s Original Pub or Backyard.',url:'https://www.kernriverbrewing.com/',link:'Explore Kern River Brewing',note:'Check current menus, opening hours, and live music listings.'},
 {id:'fishing',category:'Adventure',name:'Find your favorite bend',place:'KERN RIVER',image:'fishing',alt:'Fishing in the Kern River region',description:'Slow down with a day of fishing. Explore local guide options and learn about the river before choosing your spot.',url:'https://www.kernrivervalley.com/play',link:'Explore local recreation',note:'Check current fishing rules, permits, and river conditions.'},
 {id:'lake',category:'Nature',name:'Take the lake road',place:'LAKE ISABELLA · BEYOND TOWN',image:null,alt:'',description:'Add a lake day to your stay. Lake Isabella offers a different side of the valley, with boating, fishing, and places to enjoy a picnic.',url:'https://www.kerncounty.com/Home/Components/FacilityDirectory/FacilityDirectory/16/15202',link:'Plan a Lake Isabella outing',note:'Check current access, water conditions, and boating requirements.'},
 {id:'events',category:'Town & culture',name:'Come for the occasion',place:'KERNVILLE',image:null,alt:'',description:'From Whiskey Flat Days to seasonal festivals and Christmas in Kernville, find another reason to get away.',url:'https://explorekernville.com/main-events/',link:'See the current event calendar',note:'Dates and event programs are maintained by the organizers.'},
 {id:'trails',category:'Adventure',name:'Take the long way',place:'KERN RIVER VALLEY',image:null,alt:'',description:'Find hiking, mountain biking, and climbing around the valley. Match your outing to the weather, trail conditions, and your group’s abilities.',url:'https://www.kernrivervalley.com/play',link:'Find your next outdoor outing',note:'Check closures, route details, and conditions before your trip.'}
];
export const gallery=[{image:'river',caption:'The river sets the pace',alt:'Kern River between wooded mountain slopes'},{image:'porch',caption:'A slower kind of morning',alt:'Wooden lodge porch with green room doors'},{image:'aerial',caption:'A little closer to the wild',alt:'Aerial view of Corral Creek Lodge across the road from the Kern River'},{image:'king-clean',caption:'Make yourself at home',alt:'King studio at Corral Creek Lodge'},{image:'deck',caption:'Room to spend time together',alt:'Outdoor deck at Corral Creek Lodge'},{image:'queens-clean',caption:'Bring your favorite people',alt:'Double queen room at Corral Creek Lodge'},{image:'night',caption:'Stay a little longer',alt:'Corral Creek Lodge illuminated at night'},{image:'view',caption:'Your mountain backdrop',alt:'Mountain scenery viewed from the lodge'}];
