// Every review from the original corralcreekresort.com homepage, copied verbatim (spelling included) on 2026-09-26.
export type Review={name:string;source:'Tripadvisor'|'Expedia'|'Google'|'Booking';headline?:string;rating?:string;detail?:string;text:string[];keepsake:string};
export const guestbook:Review[]=[
 {name:'Andrey',source:'Tripadvisor',keepsake:'The hosts',text:["It's a beautiful lodge hugged by the mountains at the back and with the river at the front that makes it perfect for the morning hike. Clean rooms, convenient parking, cozy outside BBQ patio. Special appreciation to the hosts, Rebecca and Jason, who made our arrival/check-in and stay very welcoming and pleasant. Highly recommended!"]},
 {name:'Diana B',source:'Tripadvisor',keepsake:'Room 15',text:['This is a great place to stay with wonderful hosts! Mona was wonderful and so accommodating to our needs. She really made our stay the best! Thank you Mona!!','We had room 15 with 2 queen beds on the second floor. It was roomy and had everything we needed, including a fridge, microwave and a full kitchenette with pots, plans, dishes and silverware.']},
 {name:'Reelchaser',source:'Tripadvisor',keepsake:'Local lore',text:["This place is great to stay at. Half way up the upper Kern river. Great getaway! The rooms were great. Very clean and has a nice kitchenette with everything u need to cook with. Great staff. Katie checked us in and she is a wealth of information about the area. We spent about a 1/2 hr. with her talking about the history of the town and surrounding areas. She knows great places to see and also great restaurants to eat at. The continental breakfast was simple and great. They even have propane BBQ's to cook on. All in all this is a perfect remote place and the price was just right! Will definitely stay here again."]},
 {name:'jeansonnefam760',source:'Tripadvisor',keepsake:'Top floor',text:['The front desk lady was very cordial and gave us our key, we stayed on the top floor which had a beautiful view of the landscape and river form the front door. The room was clean and bed comfortable enough, the room had a kitchen area with a stove, micro, sink and a mini fridge (we forgot our Tequila so whoever came next, your welcome ;) The check in and out was easy and fast, overall we were happy with our stay and will likely choose this lodge again next time we visit Kernville.']},
 {name:'BetzyLopez',source:'Expedia',keepsake:'Trail day',text:['We had a nice time with my family, very nice staff , the room was clean with a beautiful mountain view , very close to Hiking Trails , we couldnt see the Sequoias cause the road was close but we did the Pack Saddle Trail it was a 2.8miles we could have an adventure to get until.the cave all the top of the mountain , 15mns away from the Hotel you can find Kernville town where you can have dinner to take out or outdoor dining . It was. a nice experience definetly we are coming back on Spring Break to enjoy the river and stay at Corral Creek again']},
 {name:'Cheyenne, Tehachapi',source:'Expedia',keepsake:'One more hike',text:["The staff was kind, really friendly and very accommodating! They let us leave our cars there after checking out to go hike. Only con was one of the curtains was half falling off but honestly it didn't bother us at all. Over all a great place to stay for the price."]},
 {name:'JO',source:'Expedia',keepsake:'Rest stop',text:["The location was far from town but still on the main road, making it ideal for rest after a tiring day of exploring. The river was a short walk away. The hotel room's wall is quite thin, you can hear the people conversing in the adjacent room."]},
 {name:'Sam',source:'Expedia',keepsake:'BBQ nights',text:['I really liked the outside deck with barbecues and picnic tables. Evenings were perfect outside, and being able to barbecue and eat outside was awesome. They have ice to keep your ice chests full too. Nice place in a remote wilderness with the river across the road. This will be a summer hang out for sure.']},
 {name:'Chelsea Blair',source:'Google',rating:'5/5',keepsake:'Deck grills',text:['Nice clean rooms every room has a kitchen plus there are grills on the out side deck. They are pet friendly good service excellent view and access to river across the street']},
 {name:'Vanessa Garcia',source:'Google',rating:'5/5',detail:'Family · Vacation · Service 5.0 · Location 5.0 · Rooms 5.0',keepsake:'Bailey the dog',text:['The room was very clean especially for it being a pet friendly room u would never have known pets ever stayed in it! I was especially impressed that the rooms came with everything u nd from dishes and utensils to even a dog food dish and little dish soap ! The area was very beautiful so close to a creek where the kids loved playing. The staff was very attentive and super friendly even the dog bailey made sure to do her part a d entertain my dog...lol...I highly recommend Corral Creek Lodge !!']},
 {name:'Jeremy Duncan',source:'Google',rating:'5/5',keepsake:'Feels like home',text:['great stay. The room was comfortable, cleaner than most, and welcoming, the staff was very friendly, and accomedating, and on site. friendly atmospher, with a complete kitchen, and bbq on the deck made us feel like home.I will absolutely come back.']},
 {name:'Daniel Riley',source:'Google',rating:'5/5',keepsake:'Tina & Jeremiah',text:['Corral creek has been a wonderful experience. With the beautiful, vibrant views surrounding the entire lodge there is never a dull moment. The rooms are spacious and comfortable and the accommodations are vast. Ice for sale, snacks and beverages at a good offer, and a laundry room for those extended stays. You cannot miss your chance to stay here! Not to mention the great service from Tina an Jeremiah! They are very welcoming and warm, and easy to get along with, should you want to conversate. I personally would recommend to all my family and friends and to all those looking to venture into the Kern River Valley deeper than just Isabelle or Kernville. Get out and adventure, you will find yourself at The one and only Corral Creek Lodge.']},
 {name:'Darlyn',source:'Booking',headline:'Amazing Stay!',rating:'10',keepsake:'Next to the river',text:['They provided such a great stay. Literally next to the river and just allows you to have more fun and get to come back to a clean environment. Staff were so friendly too!']},
 {name:'Darrin',source:'Booking',headline:'Exceptional',rating:'10',keepsake:'Good sleep',text:['Friendly staff. Clean room. Comfortable bed. Good location.']},
 {name:'Shoots',source:'Booking',headline:'Exceptional',rating:'10',keepsake:'1980s vibe',text:['Felt secluded but was 15 minutes from town. Room was just the right amount of space for 2 people. Kitchenette was supplied with dishes. Properly cleaned. Adorable; 1980 something family vacation vibe.']},
 {name:'Jon',source:'Booking',headline:'Very relaxing place',rating:'10',keepsake:'Four good days',text:["Super clean rooms and very comfortable beds. Views are outstanding. They are family friendly and we're able to handle our kids very well for four days."]}
];
